[project]
name = "todo-mcp-server-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ibm-watsonx-ai>=1.3.30",
    "mcp[cli]>=1.11.0",
]
